TaskManagementSystem_FinalProject/Controllers/TaskHelperController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskManagementSystem_FinalProject.Data;
using TaskManagementSystem_FinalProject.Models;

namespace TaskManagementSystem_FinalProject.Controllers
{
    [Authorize(Roles = "ProjectManager")]
    public class TaskHelperController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TaskHelperController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TaskHelper/Index
        // Hiển thị danh sách tất cả các nhiệm vụ
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.AppTask.Include(a => a.AppUser).Include(a => a.Project);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: TaskHelper/AssignTaskToProject/5
        // Hiển thị form gán nhiệm vụ vào dự án
        public IActionResult AssignTaskToProject(int id)
        {
            // Tìm nhiệm vụ cần gán dựa trên ID
            var task = _context.AppTask.First(t => t.Id == id);
            ViewBag.TaskId = task.Id;
            ViewBag.TaskName = task.Name;

            // Lấy danh sách tất cả các dự án để chọn
            var allprojects = _context.Project;
            var projectList = new SelectList(allprojects, "Id", "Name");

            return View(projectList);
        }

        // POST: TaskHelper/AssignTaskToProjectPost
        // Xử lý gán nhiệm vụ vào dự án
        [HttpPost]
        public IActionResult AssignTaskToProjectPost(int projectid, int taskid)
        {
            // Tìm nhiệm vụ cần gán và cập nhật ProjectId
            var task = _context.AppTask.First(t => t.Id == taskid);
            task.ProjectId = projectid;
            _context.Update(task);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: TaskHelper/Details/5
        // Hiển thị chi tiết nhiệm vụ
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appTask = await _context.AppTask
                .Include(a => a.AppUser)
                .Include(a => a.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appTask == null)
            {
                return NotFound();
            }

            return View(appTask);
        }

        // GET: TaskHelper/Create
        // Hiển thị form tạo mới nhiệm vụ
        public IActionResult Create()
        {
            ViewData["AppUserId"] = new SelectList(_context.AppUser, "Id", "UserName");
            ViewData["ProjectId"] = new SelectList(_context.Project, "Id", "Name");
            return View();
        }

        // POST: TaskHelper/Create
        // Xử lý tạo mới nhiệm vụ
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DeadLine,Name,CompletePercentage,Comment,ProjectId,AppUserId")] AppTask appTask)
        {
            if (ModelState.IsValid)
            {
                // Đặt DateTimeKind của DeadLine thành Utc
                appTask.DeadLine = appTask.DeadLine.ToUniversalTime();

                _context.Add(appTask);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Nếu ModelState không hợp lệ, trả về form với dữ liệu và thông báo lỗi
            ViewData["AppUserId"] = new SelectList(_context.AppUser, "Id", "UserName");
            ViewData["ProjectId"] = new SelectList(_context.Project, "Id", "Name");
            return View(appTask);
        }

        // GET: TaskHelper/Edit/5
        // Hiển thị form chỉnh sửa nhiệm vụ
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appTask = await _context.AppTask.FindAsync(id);
            if (appTask == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.AppUser, "Id", "UserName");
            ViewData["ProjectId"] = new SelectList(_context.Project, "Id", "Name");
            return View(appTask);
        }

        // POST: TaskHelper/Edit/5
        // Xử lý chỉnh sửa nhiệm vụ
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DeadLine,Id,Name,CompletePercentage,Comment,ProjectId,AppUserId")] AppTask appTask)
        {
            if (id != appTask.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Đặt DateTimeKind của DeadLine thành Utc
                    appTask.DeadLine = appTask.DeadLine.ToUniversalTime();
                    _context.Update(appTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppTaskExists(appTask.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.AppUser, "Id", "Id", appTask.AppUserId);
            ViewData["ProjectId"] = new SelectList(_context.Project, "Id", "Id", appTask.ProjectId);
            return View(appTask);
        }

        // GET: TaskHelper/Delete/5
        // Hiển thị form xác nhận xóa nhiệm vụ
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appTask = await _context.AppTask
                .Include(a => a.AppUser)
                .Include(a => a.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appTask == null)
            {
                return NotFound();
            }

            return View(appTask);
        }

        // POST: TaskHelper/Delete/5
        // Xử lý xóa nhiệm vụ
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appTask = await _context.AppTask.FindAsync(id);
            _context.AppTask.Remove(appTask);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: TaskHelper/NotFinishedAndPassedDeadlineTasks
        // Hiển thị danh sách các nhiệm vụ chưa hoàn thành và đã qua hạn
        public IActionResult NotFinishedAndPassedDeadlineTasks()
        {
            // Lấy danh sách các nhiệm vụ chưa hoàn thành
            var notCompletedtasks = _context.AppTask.Include(a => a.Project).Include(a => a.AppUser)
                                                    .Where(a => a.CompletePercentage < 100).ToList();

            var passedDeadLineTasks = new List<AppTask>();
            foreach (var task in notCompletedtasks)
            {
                // Kiểm tra các nhiệm vụ có DeadLine đã qua hạn
                if ((task.DeadLine - DateTime.Now.Date).Days < 0)
                {
                    passedDeadLineTasks.Add(task);
                }
            }
            return View(passedDeadLineTasks);
        }

        // Kiểm tra xem nhiệm vụ có tồn tại không
        private bool AppTaskExists(int id)
        {
            return _context.AppTask.Any(e => e.Id == id);
        }
    }
}

TaskManagementSystem_FinalProject/Controllers/UserManagerController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskManagementSystem_FinalProject.Data;
using TaskManagementSystem_FinalProject.Models;

namespace TaskManagementSystem_FinalProject.Controllers
{
    [Authorize(Roles = "ProjectManager")]
    public class UserManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UserManagerController(ApplicationDbContext context,
                                     UserManager<AppUser> um,
                                     RoleManager<IdentityRole> rm)
        {
            _context = context;
            userManager = um;
            roleManager = rm;
        }

        // GET: UserManager/Index
        // Hiển thị danh sách người dùng và vai trò của họ
        [Authorize(Roles = "ProjectManager")]
        public async Task<IActionResult> Index()
        {
            try
            {
                var userAndRoles = new Dictionary<AppUser, IList<string>>();
                var users = await _context.Users.ToListAsync();

                foreach (var user in users)
                {
                    var roles = await userManager.GetRolesAsync(user);
                    userAndRoles.Add(user, roles);
                }

                return View(userAndRoles);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: UserManager/AssignRoleToUser?userid={userid}
        // Hiển thị form gán vai trò cho người dùng dựa trên ID người dùng
        public async Task<IActionResult> AssignRoleToUser(string userid)
        {
            try
            {
                var user = _context.AppUser.First(u => u.Id == userid);
                var userRoles = await userManager.GetRolesAsync(user);
                var allRoles = _context.Roles.ToList();

                // Loại bỏ các vai trò mà người dùng đã có khỏi SelectList
                var otherRoles = allRoles.Where(r => !userRoles.Contains(r.ToString())).ToList();

                ViewBag.User = _context.AppUser.First(u => u.Id == userid);
                ViewBag.UserRoles = await userManager.GetRolesAsync(user);
                var selectlistOfRoles = new SelectList(otherRoles, "Name", "Name");
                return View(selectlistOfRoles);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // POST: UserManager/AssignRoleToUser
        // Xử lý gán vai trò cho người dùng
        [HttpPost]
        public async Task<IActionResult> AssignRoleToUser(string role, string userid)
        {
            try
            {
                var user = _context.Users.First(u => u.Id == userid);
                await userManager.AddToRoleAsync(user, role);
                await userManager.UpdateAsync(user);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
            return RedirectToAction("Index");
        }

        // GET: UserManager/CreateRole
        // Hiển thị form tạo mới vai trò
        public async Task<IActionResult> CreateRole()
        {
            try
            {
                var allroles = _context.Roles.ToList();
                return View(allroles);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // POST: UserManager/CreateRole
        // Xử lý tạo mới vai trò
        [HttpPost]
        public async Task<IActionResult> CreateRole(string rolename)
        {
            try
            {
                await roleManager.RoleExistsAsync(rolename);
                await roleManager.CreateAsync(new IdentityRole(rolename));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction("CreateRole");
        }

        // GET: UserManager/DeleteRole
        // Hiển thị form xóa vai trò
        public async Task<IActionResult> DeleteRole()
        {
            try
            {
                ViewBag.AllRoles = _context.Roles.ToList();
                var allroles = _context.Roles;
                var roleList = new SelectList(allroles, "Name", "Name");
                return View(roleList);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // POST: UserManager/DeleteRole
        // Xử lý xóa vai trò
        [HttpPost]
        public async Task<IActionResult> DeleteRole(string role)
        {
            try
            {
                var roleToDelete = _context.Roles.First(r => r.Name == role);
                _context.Roles.Remove(roleToDelete);
                _context.SaveChanges();
                return RedirectToAction("DeleteRole");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: UserManager/DeleteUserRole?userid={userid}
        // Hiển thị form xóa vai trò của người dùng
        public async Task<IActionResult> DeleteUserRole(string userid)
        {
            try
            {
                var user = _context.AppUser.First(u => u.Id == userid);
                var userRoles = await userManager.GetRolesAsync(user);
                var allRoles = _context.Roles.ToList();

                ViewBag.User = _context.AppUser.First(u => u.Id == userid);
                ViewBag.UserRoles = await userManager.GetRolesAsync(user);
                var selectlistOfRoles = new SelectList(userRoles);
                return View(selectlistOfRoles);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // POST: UserManager/DeleteUserRole
        // Xử lý xóa vai trò của người dùng
        [HttpPost]
        public async Task<IActionResult> DeleteUserRole(string role, string userid)
        {
            try
            {
                var roleId = _context.Roles.First(r => r.Name == role).Id;
                var userRole = _context.UserRoles.First(ur => ur.UserId == userid && ur.RoleId == roleId);
                _context.UserRoles.Remove(userRole);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: UserManager/DeleteUser
        // Hiển thị form xóa người dùng
        public async Task<IActionResult> DeleteUser()
        {
            try
            {
                ViewBag.AllUsers = _context.AppUser;
                var Alluser = _context.AppUser;
                var userList = new SelectList(Alluser, "Email", "Email");
                return View(userList);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // POST: UserManager/DeleteUser
        // Xử lý xóa người dùng
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string username)
        {
            try
            {
                var user = _context.AppUser.First(u => u.Email == username);
                var tasksOfUser = _context.AppTask.Where(t => t.AppUserId == user.Id).ToList();
                var notification = _context.Notification.Where(t => t.AppUserId == user.Id).ToList();

                // Xóa thông báo và gán lại nhiệm vụ của người dùng trước khi xóa
                foreach (var n in notification)
                {
                    n.AppUserId = default;
                }
                foreach (var task in tasksOfUser)
                {
                    task.AppUserId = null;
                }

                _context.AppUser.Remove(user);
                _context.SaveChanges();
                return RedirectToAction("DeleteUser");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: UserManager/DefineDailySalary/{id}
        // Hiển thị form định nghĩa lương hàng ngày cho người dùng
        public IActionResult DefineDailySalary(string id)
        {
            ViewBag.UserId = id;
            return View();
        }

        // POST: UserManager/DefineDailySalary/{id}
        // Xử lý định nghĩa lương hàng ngày cho người dùng
        [HttpPost]
        public IActionResult DefineDailySalary(string id, int salary)
        {
            var user = _context.AppUser.First(u => u.Id == id);
            user.DailySalary = salary;
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TaskManagementSystem_FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagementSystem_FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagementSystem_FinalProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" />

    <style>
        .navbar-nav .nav-link:hover {
            color: #fff;
        }

        .dropdown-menu .dropdown-item:hover {
            background-color: #0dcaf0;
        }

        .footer i {
            font-size: 2em; /* Kích thước biểu tượng lớn hơn */
            color: #000; /* Màu đen */
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 1.2rem; font-weight: bold;">
                    Task Management System
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <button class="nav-link text-dark btn btn-link" type="button" onclick="window.location.href='@Url.Action("Index", "Home")'">Home</button>
                        </li>

                        <li class="nav-item dropdown">
                            <button class="nav-link dropdown-toggle text-dark btn btn-link" type="button" data-bs-toggle="dropdown" aria-expanded="false">Management</button>
                            <ul class="dropdown-menu">
                                <li>
                                    <form method="post" action="/ProjectHelper/CreateNotificationFromProject">
                                        <button class="dropdown-item" type="submit">Project Helper</button>
                                        <input name="__RequestVerificationToken" type="hidden" value="CfDJ8FIHaSx6ZHhFv6sEHpUIvMOTljB2AUMdI35EJ9rWN7bophBE5yoMOK__IZMJbxq_v44Gx5mI74J8SztJSeT5ItO3uvTzxGaPrNifSwtDJ1cE4B-WQ9XRYSa9CGTXOjjjKSyHkFaEo4WDxz9xJ3Rv_V4">
                                    </form>
                                </li>
                                <li>
                                    <button class="dropdown-item btn btn-link" type="button" onclick="window.location.href='@Url.Action("Index", "UserManager")'">User Manager</button>
                                </li>
                                <li>
                                    <button class="dropdown-item btn btn-link" type="button" onclick="window.location.href='@Url.Action("Index", "TaskHelper")'">Task Helper</button>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <form method="get" action="@Url.Action("Index", "Developer")">
                                        <button class="dropdown-item" type="submit">Developer Helper</button>
                                    </form>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <button class="nav-link dropdown-toggle text-dark btn btn-link" type="button" data-bs-toggle="dropdown" aria-expanded="false">Microsoft Resources</button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-5.0">ASP.NET Core Documentation</a></li>
                                <li><a class="dropdown-item" href="https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/">C# Guide</a></li>
                                <li><a class="dropdown-item" href="https://docs.microsoft.com/en-us/dotnet/">.NET Documentation</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="https://learn.microsoft.com/en-us/training/">Microsoft Learn</a></li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <button class="nav-link text-dark btn btn-link" type="button" onclick="window.location.href='@Url.Action("Privacy", "Home")'">Privacy</button>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()   
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-between align-items-center">
            <span>&copy; 2024 - <strong>Task Management</strong> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></span>
            <div>
                <a href="https://www.youtube.com/" class="text-decoration-none me-3" target="_blank">
                    <i class="fab fa-youtube fa-2x text-dark"></i>
                </a>
                <a href="https://github.com/" class="text-decoration-none me-3" target="_blank">
                    <i class="fab fa-github fa-2x text-dark"></i>
                </a>
                <a href="https://www.facebook.com/" class="text-decoration-none me-3" target="_blank">
                    <i class="fab fa-facebook fa-2x text-dark"></i>
                </a>
                <a href="https://www.instagram.com/" class="text-decoration-none me-3" target="_blank">
                    <i class="fab fa-instagram fa-2x text-dark"></i>
                </a>     
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>